Public Profile - Farcaster Follower Count
voteagora/op-atlas pull request #430
Opened 2024-12-22 02:35 UTC by JacobHomanics

Satisfies https://github.com/voteagora/op-atlas/issues/427

2024-12-23 07:48 UTC, stepandel commented on app/src/components/profile/public/ProfileHeaderLinks.tsx
> +
same comments as with github data -- let' use `formatNumber` from the `utils`

2024-12-23 07:48 UTC, stepandel commented on app/src/components/profile/public/ProfileHeaderLinks.tsx
> +            <span className="text-sm text-[#404454]">
```suggestion
            <span className="text-sm text-gray-500">
```

2024-12-23 07:53 UTC, stepandel commented on app/src/lib/actions/neynar.ts
> +    }
this return error pattern works well when we want to inform user of an error. Fetching github data does not require user input and can / should fail silently. It's okay to send these error directly into dev console. External API calls should be able to fail without degrading user experience
tldr: let's remove the try / catch block

2024-12-23 07:54 UTC, stepandel requested changes
small nits

2025-01-02 20:58 UTC, JacobHomanics commented
Awaiting response on https://github.com/voteagora/op-atlas/pull/429#issuecomment-2568366982 as the code in this PR follows the same principles.

2025-01-02 23:28 UTC, JacobHomanics commented
should be gtg!

2025-01-03 18:51 UTC, stepandel approved these changes

2025-01-03 18:51 UTC, merged